/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package photomatonproto;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.sun.jdi.connect.spi.Connection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.beans.Statement;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;
import java.sql.*;


/**
 *
 * @author Inviter
 */
public class Photomaton extends javax.swing.JFrame {

    
    /**
     * Creates new form Photomaton
     */
    
    public Photomaton() {

    }
    
    public class jTextLimitChar extends PlainDocument {
        private int limit;
            public jTextLimitChar(int limitation){
                this.limit = limitation;
            }
                public void insertString(int offset, String str, AttributeSet set) throws BadLocationException{
                    if(str==null){
                        return;
                    }
                    else if ((getLength() + str.length()) <= limit){

                        super.insertString(offset, str, set);
                    }
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jTextField3 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Photomaton");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 224, 337, -1));

        jToggleButton1.setBackground(new java.awt.Color(255, 153, 153));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton1.setText("Quitter");
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 323, 89, -1));

        jToggleButton2.setBackground(new java.awt.Color(153, 255, 153));
        jToggleButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton2.setText("OK");
        jToggleButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 323, 89, -1));

        jLabel1.setText("N° INE : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 115, -1, -1));

        jLabel2.setText("Nom : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 171, -1, -1));

        jLabel3.setText("Prenom : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 227, -1, -1));

        jLabel4.setText("Classe : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 282, -1, -1));

        jTextField1.setDocument(new jTextLimitChar(11));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setMaximumSize(new java.awt.Dimension(7, 20));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 112, 337, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 168, 337, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("* Limiter à 11 caractères");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Photomaton L.P Roches Maigres");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 38, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel8.setText("* Developped by Hilani");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 402, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2BMEM", "2BTP", "2BMTNE", "2BMAMA", "1BTGT", "1BTEBEE", "1BTEBAA", "1CARMO", "1CIMTB", "1CPAR", "1CMACON", "1CMETAL", "1BTIPB", "1BAFB", "1BTORGO", "1BOBM", "1CMIS", "1CIFCA", "1CELEC", "1CMENU F", "1CMENU I", "1BTERA", "1BTMA", "1CABSO", "1CEBENE", "1BMA", "TBTGT", "TBTEBEE", "TBTEBAA", "TCARMO", "TCIMTB", "TCPAR", "TCMACON", "TCMETAL", "TBIPB", "TBAFB", "TBORGO", "TBOBM", "TCMIS", "TCIFCA", "TCELEC", "TBMEE", "TBMFER", "TBMELEC", "TCMENU F", "TCMENU I", "TBTERA", "TBTMA", "TCABSO", "TCEBENE", "TBMA", "BTS MS" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(7, 20));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 275, 337, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        jLabel9.setText("PHOTOMATON SCOLAIRE©");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 385, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photomatonproto/logo-4-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 367, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photomatonproto/flat-illustration-of-photographer-prepares-equipment-and-takes-a-photo-of-the-model-professionally-vector-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 112, 376, 267));

        submit.setBackground(new java.awt.Color(255, 255, 153));
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 357, 89, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        
        File nameFile = new File("Registre.csv");
        JFileChooser fc=new JFileChooser();
        fc.setSelectedFile(nameFile);
        fc.showSaveDialog(this);
        nameFile=fc.getSelectedFile();
        
        //Condition si le fichier existe
        if(!nameFile.exists()){
            try {
                nameFile.createNewFile();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        
        try {
                FileWriter ecriFichier = new FileWriter(nameFile, true);
                BufferedWriter bw = new BufferedWriter(ecriFichier);
                String getMaj = jTextField3.getText().substring(0,1).toUpperCase() + jTextField3.getText().substring(1).toLowerCase();
                bw.newLine();
                bw.write(jTextField1.getText().toUpperCase()+";"+jTextField2.getText().toUpperCase()+";"+getMaj+";"+jComboBox1.getSelectedItem()+";");
                bw.close();
                ecriFichier.close();
                JOptionPane.showMessageDialog(null,"Enregistrement des informations effectuer !");
        } 
        catch (IOException ex) {
                JOptionPane.showMessageDialog(null,"Il y a malheureusemant une erreur ici : "+ex.getMessage());
        }
       
        //Capture le flux de la webcam
        Webcam webcam = Webcam.getDefault();
        webcam.setViewSize(WebcamResolution.VGA.getSize());

        WebcamPanel panel = new WebcamPanel(webcam);
        JButton button = new JButton("Capture");
        panel.setFPSDisplayed(true);
        panel.setDisplayDebugInfo(true);
        panel.setImageSizeDisplayed(true);
        panel.setMirrored(true);
        panel.add(button);
        button.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                //Obtenir l'image de la webcam
                BufferedImage image = webcam.getImage();
                //Création de l'image 
                File outputfile = new File(jTextField1.getText().toUpperCase()+".jpg");
                //appel à l'exploration de fichier du système
                JFileChooser imgi=new JFileChooser();
                //récuperation du nom de l'image
                imgi.setSelectedFile(outputfile);
                if (!outputfile.exists()){
                    try {
                        // save image to JPG file       
                        int retVal = imgi.showSaveDialog(null);
                        if(retVal==JFileChooser.APPROVE_OPTION){

                            outputfile = imgi.getSelectedFile();
                            ImageIO.write(image,"JPG", outputfile);
                            JOptionPane.showMessageDialog(null,"Capture effectuer !");
                        }
                    
                        else if (retVal==JFileChooser.CANCEL_OPTION){
                            JOptionPane.showMessageDialog(null,"Opération anuler !");
                        }

                    } 
                    catch (IOException ex) {
                    JOptionPane.showMessageDialog(null,"Capture non effectuer il y a une erreur détecter : "+ex.getMessage());
                    }
                }
                else {
                    JOptionPane.showMessageDialog(null,"Le fichier existe !");
                }
                webcam.close();
                
            }
        });
        
        JFrame window = new JFrame("En Direct");
        window.add(panel);
        window.setResizable(true);
        window.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        window.pack();
        window.setLocationRelativeTo(null);
        window.setVisible(true);
        window.addWindowListener(new java.awt.event.WindowAdapter(){
         @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                webcam.close();
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
            }
        });
        
        

       

    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Photomaton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Photomaton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Photomaton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Photomaton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Photomaton().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
